services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    command: "start-dev"
    volumes:
      - ./data/keycloak:/opt/jboss/keycloak/standalone/data
    networks:
      - gundam
    labels:
      - "traefik.http.routers.portainer.rule=Host(`auth.localhost`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=8080"
      - "traefik.http.routers.portainer.entrypoints=web"

networks:
  gundam:
    name: gundam