services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v2.8
    networks:
      - gundam
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      # Please update with your own path
      - /mnt/wsl/shared-docker/docker.sock:/var/run/docker.sock

networks:
  gundam:
    name: gundam