services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: toor
    networks:
      - gundam
    ports:
      - 9001:9000
      - 9002:9002
    command: server --console-address ":9002"

networks:
  gundam:
    name: gundam