services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    volumes:
      - ./data:/data
    networks:
      - gundam
    ports:
      - 9001:9000
      - 9002:9002
    command: server /data --console-address ":9002"
    labels:
      - "traefik.http.routers.minio.rule=Host(`minio.localhost`)"
      - "traefik.http.services.redis.loadbalancer.server.port=9002"

networks:
  gundam:
    name: gundam