services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    networks:
      - gundam
    volumes:
      - ./data/cassandra1/app:/app/
      - ./data/cassandra1/data:/var/lib/cassandra/
  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1
    volumes:
      - ./data/cassandra2/app:/app/
      - ./data/cassandra2/data:/var/lib/cassandra/
    networks:
      - gundam

networks:
  cass:
    name: gundam