version: "3.9"

services:
  java8:
    container_name: java8
    working_dir: /app
    image: maven:3.8.6-jdk-8
    networks:
      - gundam
  java11:
    container_name: java11
    working_dir: /app
    image: maven:3.8.6-eclipse-temurin-11
    networks:
      - gundam
  java11scala:
    container_name: java11scala
    working_dir: /app
    network_mode: "host"
    build: ./image/scala
    image: batleforc/java:11scala

  java-jupy:
    container_name: java-jupy
    working_dir: /app
    image: jupyter/all-spark-notebook
    ports:
      - "8888:8888"

  java14:
    container_name: java14
    working_dir: /app
    image: maven:3.6.3-adoptopenjdk-14
    networks:
      - gundam

networks:
  gundam:
    name: gundam