services:
  go19:
    container_name: go19
    image: golang:1.19-bullseye
    networks:
      - gundam
  go18:
    container_name: go18
    image: golang:1.18-bullseye
    networks:
      - gundam

networks:
  gundam:
    name: gundam