services:
  hadoop-master:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-master
    stdin_open: true
    tty: true
    command:
      - sh
      - -c
      - service ssh start; bash -c ./start-hadoop.sh && tail -f /dev/null
    depends_on:
      - hadoop-slave1
      - hadoop-slave2
    networks:
      - hadoopBridge
    volumes:
      - C:\Users\s47960\Documents\Git\School\BigData:/app
    ports:
      - 50070:50070
      - 8088:8088
      - 707:707
  hadoop-slave1:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-slave1
    stdin_open: true
    tty: true
    networks:
      - hadoopBridge
    ports:
      - 8040:8042
  hadoop-slave2:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-slave2
    stdin_open: true
    tty: true
    networks:
      - hadoopBridge
    ports:
      - 8041:8042



networks:
  hadoopBridge:
    driver: bridge
    name: hadoopBridge