services:
  redis:
    container_name: redis-stack
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - gundam
    volumes:
      - ./data:/data
    labels:
      - "traefik.http.routers.redis.rule=Host(`redis.localhost`)"
      - "traefik.http.services.redis.loadbalancer.server.port=8001"
  rediscli:
    container_name: redis-cli
    networks:
      - gundam
    image: redis/redis-stack:latest

networks:
  gundam:
    name: gundam